<?php

// manual loader if not used with Composer
require_once __DIR__ . DIRECTORY_SEPARATOR . "BertMaurau" . DIRECTORY_SEPARATOR . "OMDB" . DIRECTORY_SEPARATOR . "Core" . DIRECTORY_SEPARATOR . "API.php";

require_once __DIR__ . DIRECTORY_SEPARATOR . "BertMaurau" . DIRECTORY_SEPARATOR . "OMDB" . DIRECTORY_SEPARATOR . "Models" . DIRECTORY_SEPARATOR . "Person.php";
require_once __DIR__ . DIRECTORY_SEPARATOR . "BertMaurau" . DIRECTORY_SEPARATOR . "OMDB" . DIRECTORY_SEPARATOR . "Models" . DIRECTORY_SEPARATOR . "Actor.php";
require_once __DIR__ . DIRECTORY_SEPARATOR . "BertMaurau" . DIRECTORY_SEPARATOR . "OMDB" . DIRECTORY_SEPARATOR . "Models" . DIRECTORY_SEPARATOR . "Director.php";
require_once __DIR__ . DIRECTORY_SEPARATOR . "BertMaurau" . DIRECTORY_SEPARATOR . "OMDB" . DIRECTORY_SEPARATOR . "Models" . DIRECTORY_SEPARATOR . "Writer.php";
require_once __DIR__ . DIRECTORY_SEPARATOR . "BertMaurau" . DIRECTORY_SEPARATOR . "OMDB" . DIRECTORY_SEPARATOR . "Models" . DIRECTORY_SEPARATOR . "Title.php";
require_once __DIR__ . DIRECTORY_SEPARATOR . "BertMaurau" . DIRECTORY_SEPARATOR . "OMDB" . DIRECTORY_SEPARATOR . "Models" . DIRECTORY_SEPARATOR . "Movie.php";
require_once __DIR__ . DIRECTORY_SEPARATOR . "BertMaurau" . DIRECTORY_SEPARATOR . "OMDB" . DIRECTORY_SEPARATOR . "Models" . DIRECTORY_SEPARATOR . "Serie.php";
require_once __DIR__ . DIRECTORY_SEPARATOR . "BertMaurau" . DIRECTORY_SEPARATOR . "OMDB" . DIRECTORY_SEPARATOR . "Models" . DIRECTORY_SEPARATOR . "SerieSeason.php";
require_once __DIR__ . DIRECTORY_SEPARATOR . "BertMaurau" . DIRECTORY_SEPARATOR . "OMDB" . DIRECTORY_SEPARATOR . "Models" . DIRECTORY_SEPARATOR . "SerieSeasonEpisode.php";
require_once __DIR__ . DIRECTORY_SEPARATOR . "BertMaurau" . DIRECTORY_SEPARATOR . "OMDB" . DIRECTORY_SEPARATOR . "Models" . DIRECTORY_SEPARATOR . "Rating.php";
require_once __DIR__ . DIRECTORY_SEPARATOR . "BertMaurau" . DIRECTORY_SEPARATOR . "OMDB" . DIRECTORY_SEPARATOR . "Models" . DIRECTORY_SEPARATOR . "Genre.php";
